"""Initial migration

Revision ID: 04ce3e2100e6
Revises: 
Create Date: 2023-09-12 21:16:11.604887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ce3e2100e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_user_id', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('google_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('google_access_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_google_user_id', ['google_user_id'])
        batch_op.create_unique_constraint('uq_google_email', ['google_email'])
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')
        batch_op.drop_column('google_email')
        batch_op.drop_column('google_user_id')

    # ### end Alembic commands ###
