"""Initial migration

Revision ID: 09d2fdf601cf
Revises: 
Create Date: 2023-09-14 23:21:16.786048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d2fdf601cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_user_id', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('uq_line_email_google_email', ['line_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_line_email_google_email', type_='unique')
        batch_op.drop_column('line_user_id')

    # ### end Alembic commands ###
