"""Add notification columns to user table

Revision ID: 0bd5cdbe924a
Revises: e6a10d0781d9
Create Date: 2023-09-23 13:21:36.361137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd5cdbe924a'
down_revision = 'e6a10d0781d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notification_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notification_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_time')
        batch_op.drop_column('is_notification_enabled')

    # ### end Alembic commands ###
